### ISSUE TITLE
Build app for ios

### ISSUE THREAD

**Issue by Anton-1408** [arpansharma7474/rn-sms-retriever#1]
Hello. I have problem where build application for IOS.
![Simulator Screen Shot - iPhone 11 - 2020-11-06 at 10 46 34](https://user-images.githubusercontent.com/40358758/98327318-78eefa00-201d-11eb-8b54-eac82e59e4db.png)

**Comment by arpansharma7474** [comment]
@Anton-1408 We have published a new version 1.1.2 with the fixes which will be available soon. Please try that.
Thanks

**Comment by Anton-1408** [comment]
@arpansharma7474  Cool. Thank!
