### ISSUE TITLE
IOS Example ?

### ISSUE THREAD

**Issue by blastering66** [arpansharma7474/rn-sms-retriever#2]
hi, i like your work. but i saw the libary ios project. Is this already library support for ios too ?
any example of that ? but the read me has note, only use in android.

**Comment by arpansharma7474** [comment]
Hey
No, this package is only for Android. Also, iOS does not support Auto OTP fill, but it allows us to show the OTP as suggestion on keyboard.

Use 

```
<TextInput
    value={this.state.codeOTP}
    textContentType="oneTimeCode"
/>
```

Starting iOS 14, this has to be first enabled in iPhone settings.

Hope It Helps!!!
